### ISSUE TITLE
Support stable release

### ISSUE THREAD

**Issue by thomas-thaulow** [Genaker/Magento2PWA#1] opened 2021-08-11 17:32 UTC
"Could not find a version of package genaker/module-pwa matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability. "

Not supporting 2.4.2 stable?..

**Comment by Genaker** [comment] 2021-08-12 06:01
Don't use composer. It has huge issues with the V1 to V2 migration. Just unzip it to the **app** folder.

**Comment by Genaker** [comment] 2021-08-12 20:43
Could you check I add stable to the composer. But the issue is you can't install it with Composer V1 you need composer V2. It is composer issue.

**Comment by Genaker** [comment] 2021-08-12 22:39
@thomas-thaulow there is an issue. New Packagist Composer packages are not available using  Composer V1. You need upgrade  Composer to V2 
```
composer self-update --2
```

See screenshot:

![composer-upgrade](https://user-images.githubusercontent.com/9213670/129278722-ef020ba3-6acc-420b-a610-d77d4b8fffa1.jpg)

**Comment by Genaker** [comment] 2021-08-12 23:20
I'm closing the issue: it is not an extension issue. it is defective PHP ecosystem.

**Closed as completed by Genaker** 2021-08-12 23:20 UTC
